### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by pauldub** [fowlmouth/nimrod-sfml#7]
After tweaking the library paths and the definition of TWindowHandle I've been able to compile the particles sample and the 'minimal' example form the ludens game engine (which uses this library). But there is an error with the opengl sample (related to the opengl wrapper). So far it is working, but the example is really simple and more testing is probably required. Would you be interested in a PR?

**Comment by fowlmouth** [comment]
No @pauldub please work with the newer package by blaxpirit https://github.com/BlaXpirit/nim-csfml
